### ISSUE TITLE
Bittorrent syncin jakelu

### ISSUE THREAD

**Issue by viljoviitanen** [haikion/afi-sync#1]
Heip,

Näyttäisi olevan kovasti bittorrent syncin ehtojen https://www.getsync.com/legal/terms-of-use kohdan 4 a (ja myös 4 b) vastaista jaella binääriä. Ehdottaisin että tää rakennetaan niin että käyttäjän pitää itse asentaa bittorrent sync, jota sitten käytetään.

**Comment by haikion** [comment]
Hei

BTSyncin foorumeiden ohjeistus on, että BTSyncciä saa jaella ohjelmiston kanssa. Linkkaamasi lisenssi kyseenalaistaa ohjeistuksen.  Kyseinen lisenssi vaikuttaa olevan jokin BitTorrent Incin yleinen lisenssi, jota sovelletaan kun parempaa ei löydy. Mitään taetta, että BTSync tuota noudattaisi ei ole. Sen sijaan http://www.bittorrent.com/legal/terms-syncapi indikoi, että BTSyncciä saa jakaa ohjelmiston kanssa. Tuntien yhdysvaltojen haastekulttuurin ohjelmistojen lisensseistä ja varsinkin pilvipalveluista voi löytyä ties mitä ehtoja, joilla yritys suojelee itseään. 

Foorumipostaukset:
https://forum.getsync.com/topic/31597-solved-can-i-distribute-btsync-with-third-party-application-that-uses-api-for-commercial/
https://forum.getsync.com/topic/31137-distribution-without-bittorent-sync-installer/
https://forum.getsync.com/topic/26482-distribution-of-executables/
https://forum.getsync.com/topic/28151-distribute-an-application-without-revealing-the-api-key/

Suljen ticketin, koska tämän tyyppinen lakikeskustelu on parempi käydä yksityisesti. Minuun voi ottaa yhteyttä Steamin kautta (nick: Hoxzer) tai sähköpostitse hoxzer(täs ät)gmail.com.
