### ISSUE TITLE
Installing userconfig fails

### ISSUE THREAD

**Issue by Cultti** [haikion/afi-sync#2]
Program does not copy @task_force_radio userconfig to Arma3 install dir. This fails because the userconfig dir does not exists in default installation.

![image](https://cloud.githubusercontent.com/assets/5057683/13556075/cd238206-e3d9-11e5-8702-c1028fb3406f.png)

Instead of checking that the destination folder exists it should create it if it does not exists.

```
58850 static void Installer::install(const QDir&, const QDir&) Nothing to install src = "E:/Pelit/arma2/@task_force_radio/userconfig"
58850 static void Installer::install(const QDir&, const QDir&) Nothing to install src = "E:/Pelit/arma2/@task_force_radio/store/userconfig"
```

**Comment by haikion** [comment]
Thank you for reporting. The bug is now fixed in 0ce6733811e3196b04aab4df31ff2c5d430763bc.  Release 0.26 will contain this fix.
